# Generated by Django 5.0 on 2023-12-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(choices=[('Friesian', 'Friesian'), ('Sahiwal', 'Sahiwal'), ('Jersey', 'Jersey'), ('Guernsey', 'Guernsey'), ('Crossbreed', 'Crossbreed'), ('Ayrshire', 'Ayrshire')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
