# Generated by Django 5.0 on 2023-12-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("reproduction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lactation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("lactation_number", models.PositiveSmallIntegerField(default=1)),
                ("actual_end_date", models.DateField(null=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lactations",
                        to="core.cow",
                    ),
                ),
                (
                    "pregnancy",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reproduction.pregnancy",
                    ),
                ),
            ],
            options={
                "get_latest_by": "-start_date",
            },
        ),
    ]
