# Generated by Django 5.0 on 2024-01-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("reproduction", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lactation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("lactation_number", models.PositiveSmallIntegerField(default=1)),
                ("actual_end_date", models.DateField(null=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lactations",
                        to="core.cow",
                    ),
                ),
                (
                    "pregnancy",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reproduction.pregnancy",
                    ),
                ),
            ],
            options={
                "get_latest_by": "-start_date",
            },
        ),
        migrations.CreateModel(
            name="Milk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_in_kgs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milk_records",
                        to="core.cow",
                    ),
                ),
                (
                    "lactation",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.lactation",
                    ),
                ),
            ],
            options={
                "get_latest_by": "-milking_date",
            },
        ),
    ]
