# Generated by Django 5.0 on 2024-01-02 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_records",
                        to="core.cow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pregnancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("date_of_calving", models.DateField(null=True)),
                (
                    "pregnancy_status",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            ("Unconfirmed", "Unconfirmed"),
                            ("Failed", "Failed"),
                        ],
                        default="Unconfirmed",
                        max_length=11,
                    ),
                ),
                ("pregnancy_notes", models.TextField(null=True)),
                ("calving_notes", models.TextField(null=True)),
                ("pregnancy_scan_date", models.DateField(null=True)),
                ("pregnancy_failed_date", models.DateField(null=True)),
                (
                    "pregnancy_outcome",
                    models.CharField(
                        choices=[
                            ("Live", "Live"),
                            ("Stillborn", "Stillborn"),
                            ("Miscarriage", "Miscarriage"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregnancies",
                        to="core.cow",
                    ),
                ),
            ],
        ),
    ]
