# Generated by Django 5.0 on 2023-12-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_in_kgs", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date_taken", models.DateField(auto_now_add=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cow"
                    ),
                ),
            ],
        ),
    ]
