# Generated by Django 5.0 on 2024-01-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CullingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Injuries", "Injuries"),
                            ("Chronic Health Issues", "Chronic Health"),
                            ("Cost Of Care", "Cost Of Care"),
                            ("Unprofitable", "Unprofitable"),
                            ("Low Market Demand", "Low Market Demand"),
                            ("Age", "Age"),
                            ("Consistent Low Production", "Consistent Low Production"),
                            ("Low Quality", "Consistent Poor Quality"),
                            (
                                "Inefficient Feed Conversion",
                                "Inefficient Feed Conversion",
                            ),
                            ("Inherited Diseases", "Inherited Diseases"),
                            ("Inbreeding", "Inbreeding"),
                            ("Unwanted Traits", "Unwanted Traits"),
                            ("Climate Change", "Climate Change"),
                            ("Natural Disaster", "Natural Disaster"),
                            ("Overpopulation", "Overpopulation"),
                            ("Government Regulations", "Government Regulations"),
                            ("Animal Welfare Standards", "Animal Welfare Standards"),
                            (
                                "Environmental Protection Laws",
                                "Environment Protection Laws",
                            ),
                        ],
                        max_length=35,
                    ),
                ),
                ("notes", models.TextField(max_length=100, null=True)),
                ("date_carried", models.DateField(auto_now_add=True)),
                (
                    "cow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culling_record",
                        to="core.cow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_in_kgs", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date_taken", models.DateField(auto_now_add=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cow"
                    ),
                ),
            ],
        ),
    ]
